const translations = {
    "en": {
        "nav_home": "Home",
        "nav_about": "About Us",
        "breadcrumb_home": "Home",
        "nav_business": "Our Business",
        "nav_sustainability": "Sustainability",
        "nav_news": "Latest News",
        "nav_careers": "Careers",
        "nav_contact": "Contact Us",
        "completed_projects": "Signature Projects",
        "btn_switch_en": "EN",
        "btn_switch_zh": "繁",
        "btn_switch_cn": "简",
        "footer_intro": "Orientfunds Precast Limited was established in 1998, specializing in the production and supply of precast concrete components.",
        "footer_quick_links": "Quick Links",
        "footer_contact_title": "Contact Us",
        "footer_headquarters": "Headquarters:",
        "footer_factory": "Dongguan Factory:",
        "footer_copyright": "© 2026 Orientfunds Precast Ltd. All Rights Reserved.",
        "hero_title": "Overcoming Difficulties, Blazing New Trails",
        "index_about_title": "About Orientfunds",
        "index_about_desc": "Orientfunds Precast Limited is a company specializing in precast components, upholding the spirit of 'Building Homes from the Heart', bravely overcoming difficulties and constantly blazing new trails. We adhere to professionalism and innovation as our core, committed to providing clients with high-quality and reliable construction solutions.",
        "btn_learn_more": "Learn More ▶",
        "section_projects": "Engineering Projects",
        "section_strength": "Company Strength",
        "stat_years": "Years Experience",
        "stat_projects": "Successful Projects",
        "stat_factory": "Sqm Factory",
        "cta_title": "Company Strength",
        "cta_desc": "Learn more about our services and projects",
        "btn_contact_us": "Contact Us",
        "about_title": "About Us",
        "about_intro_title": "Company Introduction",
        "about_profile_title": "Company Profile",
        "about_profile_desc": "Orientfunds Precast Limited was established in 1998. Our factory is located in Shatian Town, Dongguan City. It is a wholly-owned enterprise with an investment of over HK$80 million, covering an area of over 80,000 square meters, with natural waterways and convenient water transportation.",
        "about_location_title": "Factory Location",
        "about_location_desc": "The Dongguan factory is 100km from Hong Kong with a complete transportation network. The factory is located at the entrance of Shiziyang, Pearl River. It takes only 6 hours to reach Hong Kong by sea. It takes 2 hours to reach Hong Kong from Huanggang or Man Kam To by land.",
        "about_hongfai_title": "About Orientfunds",
        "about_hongfai_desc": "Since its establishment in 1998, Orientfunds has focused on high-quality manufacturing and cross-border services. The company established a modern factory in Shatian, Dongguan, built along the water. Its superior geographical location and natural proximity to waterways provide unique advantages for efficient transportation. The factory is only over 100 kilometers from Hong Kong, with a well-developed transportation network. Water transport to Hong Kong takes about 6 hours, and it takes only just over three hours by car via Huanggang, Liantang, or Shenzhen Bay ports. Leveraging this strategic location, Orientfunds can rapidly connect Guangdong and Hong Kong, providing efficient and reliable cross-border supply chain support for its partners.<br><br>Orientfunds possesses comprehensive production and logistics facilities, including a concrete plant, storage yards, sand and gravel warehouses, and ten all-weather production workshops. Even in adverse weather conditions, it can maintain high-efficiency operations, ensuring quality and progress. The factory area is equipped with movable canopies, electric concrete vehicles, and skid steer loaders to enhance production and finishing efficiency. The storage area covers 25,000 square meters and is currently used for storing precast facade elements. The company also has an independent pier capable of handling products weighing over 30 tons and accommodating large vessels. Combined with mature land transportation, this ensures unimpeded transport by both sea and land.",
        "core_values": "Core Values",
        "facilities": "Facilities",
        "zone_one_title": "Zone One - Main Production of Building Prefabricated Components",
        "zone_one_desc": "Zone one consists of 5 covered workshops, storage yards and concrete batching plant. The 5 covered workshops ensure high quality and on-time production under all weather conditions. We are capable of producing precast products equivalent to 25 building blocks simultaneously, i.e., handling at least 100 sets of molds, with daily production exceeding 700 tons.",
        "zone_two_title": "Zone Two - Segment / Large Precast Products",
        "zone_two_desc": "Zone Two casting yard and storage yard cover 25,000 m². It is equipped with 2 gantry cranes (80T and 50T each). It functions for the production of heavy precast units e.g. segments, large precast beams/columns and facades, noise barrier panels etc.",
        "jetty_title": "Jetty",
        "jetty_desc": "Our jetty can take in barge over 10,000 tons. There are 2 sets of fixed cranes (150T and 80T), convenient for loading large precast components.",
        "tech_advantage_title": "Technical Advantage",
        "tech_advantage_desc": "Regular Precast Workshops held with remarkable institutes (e.g. HKU, PolyU) and organizations.",
        "business_products_title": "Products",
        "prod_mic": "MiC Modular Integrated Construction",
        "prod_wall_panel": "Lightweight Concrete Wall Panel",
        "prod_facade": "Façade",
        "prod_steel_mic": "Steel MiC",
        "prod_steel_mic_ext": "Steel MiC (Exterior)",
        "prod_steel_mic_int": "Steel MiC (Interior)",
        "prod_conc_mic": "Concrete MiC",
        "prod_conc_mic_ext": "Concrete MiC (Exterior)",
        "prod_conc_mic_int": "Concrete MiC (Interior)",
        "prod_stair": "Staircase",
        "prod_balcony": "Balcony",
        "prod_ext_wall": "External Wall",
        "prod_chute": "Refuse Chute",
        "prod_semi_slab": "Semi-precast Slab",
        "prod_conc_slab": "Retaining Wall Panel",
        "proj_keitak": "Kai Tak",
        "proj_cullinan_harbour": "Cullinan Harbour",
        "proj_tinshuiwai": "Tin Shui Wai",
        "proj_yoho_west": "Yoho West",
        "proj_saisha": "Sai Sha",
        "proj_sierra_sea": "Sierra Sea",
        "proj_cullinan_sky": "Cullinan Sky",
        "proj_tuenmun": "Tuen Mun",
        "proj_novoland": "NOVOLAND",
        "proj_tsuenwan": "Tsuen Wan",
        "proj_1_sha_tsui_rd": "Global Plaza",
        "proj_pakshekkok": "Pak Shek Kok",
        "proj_university_hill": "University Hill",
        "proj_yuenlong": "Yuen Long",
        "proj_hakopo_mockup": "Concrete MiC Units Mockup - Ha Ko Po Tsuen",
        "proj_go_aqua": "Go Aqua",
        "proj_hakopo_hybrid_office": "Hybrid MiC Site Office - Ha Ko Po Tsuen",
        "proj_yoho_hub_2": "The YOHO Hub Phase 2",
        "proj_shatin": "Shatin",
        "proj_shatin_name": "St Michel",
        "proj_taikoktsui": "Tai Kok Tsui",
        "proj_taikoktsui_name": "Le Moment",
        "proj_tsingyi": "Tsing Yi",
        "proj_tsingyi_name": "The Grand Marine",
        "proj_southisland": "Island South",
        "proj_southisland_name": "La Marina",
        "proj_saiyingpun": "Sai Ying Pun",
        "proj_saiyingpun_name": "15 Western Street",
        "proj_year_kaitak_harbour": "Completed in 2024",
        "proj_year_2025": "Completed in 2025",
        "proj_year_2024": "Completed in 2024",
        "proj_year_tinshuiwai": "Completed in 2024",
        "proj_year_saisha": "Completed in 2024",
        "proj_year_kaitak_sky": "Completed in 2023",
        "proj_year_novoland": "Completed in 2023",
        "proj_year_sha_tsui_rd": "Completed in 2021",
        "proj_year_university_hill": "Completed in 2022",
        "proj_year_yoho_hub_2": "Completed in 2022",
        "proj_year_st_michel": "Completed in 2021",
        "proj_year_le_moment": "Completed in 2020",
        "proj_year_grand_marine": "Completed in 2021",
        "proj_year_la_marina": "Completed in 2021",
        "recent_projects_title": "Projects Completed in the Last 5 Years",
        "proj_2025_1": "2~8 Mansfield Road, The Peak",
        "proj_2025_2": "Central Residence by the Park",
        "proj_2025_3": "CLOUDVIEW",
        "proj_2025_4": "DEEP WATER PAVILIA",
        "proj_2025_5": "eResidence",
        "proj_2025_6": "foto+",
        "proj_2025_7": "FSST Lot no.278, Kwu Tung",
        "proj_2025_8": "Kai Tak Area 2B1",
        "proj_2024_1": "Concrete MiC Units Mockup - Ha Ko Po Tsuen, Yuen Long",
        "proj_2024_2": "Cullinan Harbour",
        "proj_2024_3": "GO PARK Aqua",
        "proj_2024_4": "Hybrid MiC Site Office - Ha Ko Po Tsuen, Yuen Long",
        "proj_2024_5": "Hybrid MiC Site Office - Kwu Tung North (Area 25)",
        "proj_2024_6": "T.M.T.L No.496, So Kwun Wat, Tuen Mun",
        "proj_2024_7": "Sierra Sea Phase 1",
        "proj_2024_8": "YOHO WEST",
        "proj_2023_1": "Chung Yuet Lau, Jat Min Chuen, Sha Tin",
        "proj_2023_2": "Cullinan Sky",
        "proj_2023_3": "Kingview Plaza",
        "proj_2023_4": "NOVO LAND Phase 2",
        "proj_2023_5": "NOVO LAND Phase 3",
        "proj_2023_6": "Sierra Sea Phase 2A",
        "proj_2022_1": "MONTEGO BAY",
        "proj_2022_2": "NOVO LAND Phase 1",
        "proj_2022_3": "ONE SOHO",
        "proj_2022_4": "The Knightsbridge",
        "proj_2022_5": "The YOHO Hub",
        "proj_2022_6": "University Hill",
        "proj_2021_1": "233 Prince Edward Road West",
        "proj_2021_2": "Global Plaza",
        "proj_2021_3": "KENNEDY 38",
        "proj_2021_4": "La Marina",
        "proj_2021_5": "Madera Garden",
        "proj_2021_6": "ONE INNOVALE",
        "proj_2021_7": "The Grand Marine",
        "proj_2021_8": "THE HARMONIE",
        "proj_2021_9": "The Met. Azure",
        "proj_2021_1_dev": "Sun Hung Kai Properties / Wheelock Properties",
        "proj_2021_2_dev": "Billion Development and Project Management Limited",
        "proj_2021_3_dev": "SUN HUNG KAI / WHEELOCK / HENDERSON",
        "proj_2021_4_dev": "SINO GROUP / MTR CORPORATION / KERRY PROPERTIES",
        "proj_2021_5_dev": "Hip Shing Hong",
        "proj_2021_6_dev": "HENDERSON",
        "proj_2021_7_dev": "Grand Ming Group",
        "proj_2021_8_dev": "URBAN RENEWAL AUTHORITY / HENDERSON",
        "proj_2021_9_dev": "Wang On Properties",
        "related_business_title": "Related Business",
        "related_concrete_title": "Concrete",
        "related_concrete_desc": "Our sister company - Glorious Concrete (H.K.) Ltd., specializes in the production and supply of high-quality concrete and precast components. With comprehensive production facilities and strict quality control, Glorious Concrete provides stable and reliable building material support for close partners. Through collaboration between departments, we ensure construction progress and cost-effectiveness, while promoting the application of innovative technologies to build a solid foundation for various construction projects.",
        "website_label": "Website",
        "qualifications_title": "Professional Qualifications",
        "qualifications_placeholder": "Content for professional qualifications will be added here.",
        "business_title": "Our Business",
        "eng_projects": "Engineering Projects",
        "cat_residential": "Residential Buildings",
        "cat_infrastructure": "Infrastructure",
        "cat_domestic": "Domestic/Macau",
        "tbl_project_name": "Project Name",
        "tbl_product": "Precast Concrete Product",
        "tbl_developer": "Developer",
        "tbl_period": "Construction Period",
        "sus_title": "Sustainability",
        "env_commitment_title": "Environmental Commitment",
        "env_commitment_desc": "We recognize that urban development must progress hand in hand with environmental stewardship. Orientfunds continuously drives innovation and improvement to minimize the environmental impact of construction, safeguarding a sustainable ecosystem for society and future generations.",
        "qm_cert_title": "Quality Management & Certification",
        "qm_cert_desc_1": "We ensure the quality of every precast component through rigorous processes. From raw material inspection and factory production to on-site installation, we adhere to international and local standards with multiple inspection checkpoints. Through intelligent equipment and precise monitoring, we ensure dimensional accuracy and stable performance, providing reliable, safe, and sustainable building solutions for our partners.",
        "qm_cert_desc_2": "OPL has been awarded ISO9001 and ISO14001 certifications by the HKQAA for design, production, quality, and environmental protection, fully affirming our professional standards. Meanwhile, our Dongguan factory's Occupational Health and Safety Management has been assessed and certified by the Elvey Quality Certification Center, further demonstrating our commitment to safety and responsibility.",
        "env_protect_title": "Environmental Protection",
        "env_protect_desc": "OPL is committed to implementing environmental protection and sustainability practices in all business operations.",
        "qm_title": "Quality Management",
        "qm_policy_title": "Quality Policy",
        "qm_policy_desc": "It is the objective of Orientfunds Precast Limited to operate in accordance with the requirements of ISO9001, to produce and supply precast concrete products to the satisfaction of customers.",
        "qm_control_title": "Quality Control",
        "qm_control_desc": "Comprehensive Quality Inspection System: Incoming Material Inspection, In-process Inspection, Finished Product Inspection.",
        "tbl_level_1": "Level 1",
        "tbl_level_2": "Level 2",
        "tbl_level_3": "Level 3",
        "cert_title": "Quality Certification",
        "cert_desc": "ISO9001 & 14001 Certificates are accredited to OPL by HKQAA. OPL is one of the QSPSC certified precast concrete producers.",
        "careers_title": "Careers",
        "join_us_title": "Join Us",
        "join_us_desc": "At Orientfunds, we value talent development and provide excellent working environment and professional growth opportunities.",
        "job_eng_title": "Engineering Positions",
        "job_eng_desc": "Looking for experienced engineers to join our team.",
        "job_qc_title": "Quality Control",
        "job_qc_desc": "Responsible for product quality inspection and control.",
        "job_pm_title": "Project Management",
        "job_pm_desc": "Manage large-scale construction projects and coordinate team resources.",
        "job_opp_title": "Job Opportunities",
        "job_opp_desc_1": "We invite aspiring individuals to join our team and explore the future together. We value talent and provide comprehensive training, benefits, and competitive remuneration packages. To apply, please click \"<a href='#' style='color:#4CAF50; text-decoration:underline;'>Apply Here</a>\" and complete the online application form.",
        "job_opp_desc_2": "All job applications will be treated in strict confidence by authorized personnel and used for recruitment purposes only. Applicants not contacted within three months after the deadline may consider their applications unsuccessful. We will safely destroy the data of all unsuccessful applicants after six months. In case of any discrepancy between the English and Chinese versions, the English version shall prevail.",
        "interested_title": "Interested in joining us?",
        "interested_desc": "Please contact us to learn more about job opportunities.",
        "contact_title": "Contact Us",
        "general_inquiry": "General Inquiry",
        "head_office": "Head Office",
        "domestic_address": "Domestic Address",
        "contact_page_title": "Contact Us",
        "contact_hq": "Head Office",
        "contact_factory": "Dongguan Factory",
        "contact_hq_full": "Orientfunds Precast Limited (Head Office)",
        "contact_factory_full": "Dongguan Orientfunds Construction Materials Products Co., Ltd. (Dongguan Factory)", 
        "contact_hq_address": "Address: Units Nos. 2201-2211 and 2220-2225, Level 22, Tower 1, Metroplaza, 223 Hing Fong Road, Kwai Fong, N.T.",
        "contact_hq_tel": "Tel: (852) 2559 5765",
        "contact_hq_fax": "Fax: (852) 2517 0873",
        "contact_hq_email": "Email: opl-enquiry@orientfunds.com.hk",
        "contact_factory_address": "Address: No.3 Lianjian Road, Shatian Town, Dongguan, Guangdong, China Postal Code: 523990",
        "contact_factory_tel": "Tel: (86) 769 8886 8880",
        "contact_factory_fax": "Fax: (86) 769 8886 8820",
        "val_title": "Core Values",
        "val_goal_title": "Goal",
        "val_goal_desc": "To be the most reliable precast component supplier in urban development. Every precast element is a cornerstone carrying the dreams of the city. Through quality, innovation, and responsibility, we make bridges, high-rises, and roads stronger and better.",
        "val_mission_title": "Mission",
        "val_combined_title": "Goal, Mission, Vision",
        "val_mission_desc": "To inject urban vitality with high-quality concrete and Innobond building materials. We commit to providing our partners with reliable, timely, and competitive support, delivering safe, eco-friendly, and sustainable construction materials that will stand the test of time for future generations.",
        "val_vision_title": "Vision",
        "val_vision_desc": "To become Hong Kong's most influential green building materials brand, driving cities toward a low-carbon future. Through intelligent supply chains and professional distribution services, we advance technology and sustainability side by side, carrying the dreams and hopes of generations.",
        "mile_title": "Milestones",
        "milestone_desc_1998": "Company established, focusing on Housing Authority and Housing Society projects.",
        "milestone_desc_2002": "Expanded into private sector, undertaking major private construction projects.",
        "milestone_desc_2019": "Began R&D on MiC technology, launched the first Orientfunds Concrete MiC product.",
        "milestone_desc_2022": "Successfully developed and introduced Low-density Concrete Partition to the market.<br><br>Achieved HKQAA Net-Zero Emission Certification and was recognized as a pioneering organization in advancing net-zero carbon initiatives.",
        "milestone_desc_2023": "Initiated R&D on Hybrid/Concrete MiC, branded as \"Light Comfy House\".",
        "milestone_desc_2024": "Secured patent for fully prefabricated Low-density Concrete Partition.",
        "awards_title": "Awards & Recognition",
        "awards_desc": "Received multiple industry certifications and recognitions.",
        "sister_title": "Related Company",
        "sister_desc": "Glorious Concrete (H.K.) Limited and Orientfunds Precast Limited. are related companies headquartered in Hong Kong, specializing in the concrete industry. Both enterprises uphold the values of professionalism and innovation, delivering high-quality concrete products and solutions across construction, infrastructure, and diverse engineering projects. Leveraging Hong Kong’s strategic location and comprehensive logistics network, we efficiently meet customer needs while continuously expanding their business footprint.",
        "website_label": "Website: ",
        "about_hongfai_title": "About Orientfunds",
        "about_hongfai_desc": "Since its establishment in 1998, Orientfunds has focused on high-quality manufacturing and cross-border services. The company established a modern factory in Shatian, Dongguan, built along the water. Its superior geographical location and natural proximity to waterways provide unique advantages for efficient transportation. The factory is only over 100 kilometers from Hong Kong, with a well-developed transportation network. Water transport to Hong Kong takes about 6 hours, and it takes only just over three hours by car via Huanggang, Liantang, or Shenzhen Bay ports. Leveraging this strategic location, Orientfunds can rapidly connect Guangdong and Hong Kong, providing efficient and reliable cross-border supply chain support for its partners.<br><br>Orientfunds possesses comprehensive production and logistics facilities, including a concrete plant, storage yards, sand and gravel warehouses, and ten all-weather production workshops. Even in adverse weather conditions, it can maintain high-efficiency operations, ensuring quality and progress. The factory area is equipped with movable canopies, electric concrete vehicles, and skid steer loaders to enhance production and finishing efficiency. The storage area covers 25,000 square meters and is currently used for storing precast facade elements. The company also has an independent pier capable of handling products weighing over 30 tons and accommodating large vessels. Combined with mature land transportation, this ensures unimpeded transport by both sea and land.",
        "cert_patent_title": "Qualifications and Patents",
        "iso_desc": "ISO Certification: Audited by third-party organizations to ensure the management system meets international standards.",
        "patent_desc": "Patents: Granted by the government to protect exclusive rights to technology or design.",
        "pqm_title": "Precast Quality Management",
        "pqm_section_title": "High-Quality Precast Components for a Low-Carbon Future",
        "pqm_desc": "We ensure the quality of every precast component through a rigorous process. From raw material inspection and factory production to on-site installation, we adhere to international and local standards with multiple testing stages. Supported by intelligent equipment and precise monitoring, our components achieve exact dimensions and superior performance, significantly reducing on-site waste and rework — thereby lowering overall carbon emissions and delivering reliable, safe, and genuinely sustainable green building solutions for our partners.",
        "iso14001_text": "ISO 14001:2015<br>Certificate No: CC 5665",
        "iso9001_text": "ISO 9001:2015<br>Certificate No: CC 1538",
        "net_zero_title": "Pioneering Organization in Net-Zero Contribution",
        "net_zero_desc": "In 2022, Orientfunds formalized its commitment under the Net-Zero Certificate Scheme administered by the Hong Kong Quality Assurance Agency (HKQAA). As a result of these efforts, Orientfunds was recognized as a pioneering organization for its outstanding contribution to advancing net-zero carbon initiatives, highlighting its leadership role in promoting sustainable development within the industry.",
        "three_inspection_title": "The Trio Inspections",
        "three_inspection_section_title": "Trio Inspection System for Durable Low-Carbon Buildings",
        "three_inspection_desc": "Our Quality Assurance Team rigorously monitors every product to ensure only high-quality, durable items are delivered. The company fully implements the “Trio Inspection” system — Self-Inspection, Re-Inspection, and Special Inspection — to guarantee consistent quality. The Production and Quality Teams handle self- and re-inspection, while the Zhongshan Office conducts weekly special inspections at the Dongguan factory. This multi-level mechanism significantly reduces defects and future repair needs, extending building lifespan and lowering lifecycle carbon emissions — delivering genuine long-term protection for the environment.",
        "insp_self": "Self-inspection (Production Dept)",
        "insp_re": "Re-inspection (Quality Team)",
        "insp_special": "Special Inspection (Zhongshan Office)",
        "traceability_title": "Strict check point",
        "traceability_section_title": "Strict Checkpoint Traceability System to Minimize Resource Waste",
        "traceability_desc": "Orientfunds adheres to the “Strict Checkpoint” principle, using QR codes for full traceability throughout the production process. From Rebar fixing and mold installation to concreting, rectification, and final inspection, every step is digitally recorded. Should any issue arise later, the system instantly traces back to the responsible workers and inspectors. This precise traceability prevents rework and material waste, reduces the carbon footprint of production, and ensures every product truly meets environmental and sustainable standards."
    },
    "zh": {
        "nav_home": "首頁",
        "nav_about": "關於我們",
        "breadcrumb_home": "主頁",
        "nav_business": "公司業務",
        "nav_sustainability": "可持續發展",
        "nav_news": "最新動態",
        "nav_careers": "事業發展",
        "nav_contact": "聯絡我們",
        "completed_projects": "我們參與的著名項目",
        "btn_switch_en": "EN",
        "btn_switch_zh": "繁",
        "btn_switch_cn": "简",
        "footer_intro": "鴻輝預製件有限公司成立於1998年，專門從事預製混凝土構件的生產和供應。",
        "footer_quick_links": "快速連結",
        "footer_contact_title": "聯絡我們",
        "footer_headquarters": "總公司：",
        "footer_factory": "東莞廠房：",
        "footer_copyright": "Copyright © 2026鴻輝預製件有限公司．版權所有。",
        "hero_title": "克服困難，開拓新路",
        "index_about_title": "關於鴻輝",
        "index_about_desc": "鴻輝是一家專注於預製件的公司，秉承「以心建家」的精神，勇於克服困難，不斷開拓新路。我們堅持以專業與創新為核心，致力為客戶提供優質可靠的建築解決方案。",
        "btn_learn_more": "了解更多 ▶",
        "section_projects": "工程項目",
        "section_strength": "公司實力",
        "stat_years": "年專業經驗",
        "stat_projects": "成功項目",
        "stat_factory": "平方米廠房",
        "cta_title": "公司實力",
        "cta_desc": "了解更多關於我們的服務和項目",
        "btn_contact_us": "聯絡我們",
        "about_title": "關於我們",
        "about_intro_title": "公司簡介",
        "about_profile_title": "公司概況",
        "about_profile_desc": "鴻輝預製件有限公司成立於1998年。我們的工廠位於東莞市沙田鎮。我們是一家全資企業，投資超過8000萬港元，佔地面積超過80,000平方米，擁有天然水道，水路運輸便利。",
        "about_location_title": "廠房位置",
        "about_location_desc": "東莞廠房距離香港100公里，交通網絡完善。廠房位於珠江獅子洋入口處。海路前往香港僅需6小時。經陸路從皇崗或文錦渡前往香港需時2小時。",
        "core_values": "核心價值",
        "facilities": "設施",
        "zone_one_title": "第一工區 - 主力生產樓宇預製件",
        "zone_one_desc": "第一工區由5個有蓋車間、堆場和混凝土攪拌站組成。5個有蓋車間確保在各種天氣條件下的高質量和準時生產。我們有能力同時生產相當於25座樓宇的預製產品，即處理最少100套模具，日產量超过700噸。",
        "zone_two_title": "第二工區 - 大型構件生產",
        "zone_two_desc": "第二工區鑄造場和堆場佔地25,000平方米。配備2台龍門吊機（各80噸和50噸）。主要用於生產重型預製構件，如管片、大型預製樑/柱和外牆、隔音屏障板等。",
        "jetty_title": "碼頭",
        "jetty_desc": "我們的碼頭可停靠超過10,000噸的駁船。配有2套固定吊機（150噸和80噸），方便裝載大型預製構件。",
        "tech_advantage_title": "技術優勢",
        "tech_advantage_desc": "定期與知名機構（如香港大學、理工大學）及組織舉辦預製件研討會。",
        "business_products_title": "產品",
        "prod_mic": "MiC組裝合成建築法",
        "prod_wall_panel": "輕質混凝土間牆板",
        "prod_facade": "佛沙",
		"prod_steel_mic": "鋼結構組裝合成建築法",
        "prod_steel_mic_ext": "鋼結構組裝合成建築法 (外觀)",
        "prod_steel_mic_int": "鋼結構組裝合成建築法 (室內裝修)",
        "prod_conc_mic": "全混凝土組裝合成建築法",
        "prod_conc_mic_ext": "全混凝土組裝合成建築法 (外觀)",
        "prod_conc_mic_int": "全混凝土組裝合成建築法 (室內裝修)",
        "prod_stair": "樓梯",
        "prod_balcony": "露台",
        "prod_ext_wall": "外牆",
        "prod_chute": "垃圾槽",
        "prod_semi_slab": "半樓板",
        "prod_conc_slab": "擋土牆板",
        "proj_keitak": "啟德",
        "proj_cullinan_harbour": "天璽 • 海",
        "proj_tinshuiwai": "天水圍",
        "proj_yoho_west": "Yoho West",
        "proj_saisha": "西沙",
        "proj_sierra_sea": "Sierra Sea",
        "proj_cullinan_sky": "天璽 • 天",
        "proj_tuenmun": "屯門",
        "proj_novoland": "NOVOLAND",
        "proj_tsuenwan": "荃灣",
        "proj_1_sha_tsui_rd": "環貿廣場",
        "proj_pakshekkok": "白石角",
        "proj_university_hill": "University Hill",
        "proj_yuenlong": "元朗",
        "proj_hakopo_mockup": "下高埔村全混凝土MiC示範單位",
        "proj_go_aqua": "Go Aqua",
        "proj_hakopo_hybrid_office": "下高埔鋼結構MiC寫字樓",
        "proj_yoho_hub_2": "The YOHO Hub 2期",
        "proj_shatin": "沙田",
        "proj_shatin_name": "瓏珀山",
        "proj_taikoktsui": "大角咀",
        "proj_taikoktsui_name": "傲寓",
        "proj_tsingyi": "青衣",
        "proj_tsingyi_name": "明翹匯",
        "proj_southisland": "港島南",
        "proj_southisland_name": "揚海",
        "proj_saiyingpun": "西營盤",
        "proj_saiyingpun_name": "西邊街15號",
        "proj_year_kaitak_harbour": "2024年建成",
        "proj_year_2025": "2025年建成",
        "proj_year_2024": "2024年建成",
        "proj_year_tinshuiwai": "2024年建成",
        "proj_year_saisha": "2024年建成",
        "proj_year_kaitak_sky": "2023年建成",
        "proj_year_novoland": "2023年建成",
        "proj_year_sha_tsui_rd": "2021年建成",
        "proj_year_university_hill": "2022年建成",
        "proj_year_yoho_hub_2": "2022年建成",
        "proj_year_st_michel": "2021年建成",
        "proj_year_le_moment": "2020年建成",
        "proj_year_grand_marine": "2021年建成",
        "proj_year_la_marina": "2021年建成",
        "recent_projects_title": "近5年內完成的工程項目",
        "proj_2025_1": "山頂文輝道2-8號",
        "proj_2025_2": "雅盈峰",
        "proj_2025_3": "雲向",
        "proj_2025_4": "滶晨 - 港島南岸5A期",
        "proj_2025_5": "煥然懿居",
        "proj_2025_6": "映居",
        "proj_2025_7": "古洞第278地段",
        "proj_2025_8": "啟德第2B1區",
        "proj_2024_1": "MiC 單位Mockup - 元朗下高埔村",
        "proj_2024_2": "天璽·海",
        "proj_2024_3": "GO PARK Aqua",
        "proj_2024_4": "MiC地盤寫字樓 - 元朗下高埔村",
        "proj_2024_5": "MiC地盤寫字樓 - 古洞北 (Area 25)",
        "proj_2024_6": "屯門掃管笀第496號地段",
        "proj_2024_7": "Sierra Sea 第1期",
        "proj_2024_8": "YOHO WEST",
        "proj_2023_1": "沙田乙明邨松悅樓",
        "proj_2023_2": "天璽·天",
        "proj_2023_3": "京匯廣場",
        "proj_2023_4": "NOVO LAND 第2期",
        "proj_2023_5": "NOVO LAND 第3期",
        "proj_2023_6": "Sierra Sea 第2A期",
        "proj_2022_1": "蔚藍東岸",
        "proj_2022_2": "NOVO LAND 第1期",
        "proj_2022_3": "ONE SOHO",
        "proj_2022_4": "天瀧",
        "proj_2022_5": "The YOHO Hub",
        "proj_2022_6": "University Hill",
        "proj_2021_1": "太子道西233號",
        "proj_2021_2": "環貿廣場",
        "proj_2021_3": "KENNEDY 38",
        "proj_2021_4": "揚海",
        "proj_2021_5": "芳菲",
        "proj_2021_6": "ONE INNOVALE",
        "proj_2021_7": "明翹匯",
        "proj_2021_8": "映築",
        "proj_2021_9": "薈藍",
        "proj_2021_1_dev": "新鴻基地產/會德豐地產",
        "proj_2021_2_dev": "億京發展及策劃有限公司",
        "proj_2021_3_dev": "恆基兆業、新鴻基地產及會德豐地產",
        "proj_2021_4_dev": "信置 / 港鐵 / 嘉里建設",
        "proj_2021_5_dev": "協成行",
        "proj_2021_6_dev": "恒基兆業地產",
        "proj_2021_7_dev": "佳明集團",
        "proj_2021_8_dev": "市建局/恒基兆業",
        "proj_2021_9_dev": "宏安地產",
        "related_business_title": "相關業務",
        "related_concrete_title": "混凝土",
        "related_concrete_desc": "我們的姊妹公司 - 永輝混凝土(香港)有限公司，專注於高品質混凝土及預製組件的生產與供應。憑藉完善的生產設施與嚴格的品質監控，永輝混凝土為緊密的合作夥伴提供穩定、可靠的建材支持。透過各部門協作，我們確保施工進度與成本效益，同時推動創新技術的應用，為各類建築項目打造堅實基礎。",
        "website_label": "網站",
        "qualifications_title": "專業資格",
        "qualifications_placeholder": "專業資格內容將在此處添加。",
        "business_title": "公司業務",
        "eng_projects": "工程項目",
        "cat_residential": "住宅樓宇",
        "cat_infrastructure": "基建",
        "cat_domestic": "國內澳門",
        "tbl_project_name": "項目名稱",
        "tbl_product": "預製混凝土產品",
        "tbl_developer": "發展商",
        "tbl_period": "施工期",
        "sus_title": "可持續發展",
        "env_commitment_title": "環境承諾",
        "env_commitment_desc": "我們深知城市發展必須兼顧環境保護，鴻輝持續推動創新與改進，減少建築對自然的影響，為社會與未來世代守護可持續的生態。",
        "qm_cert_title": "質量管理及品質認證",
        "qm_cert_desc_1": "我們以嚴謹的流程確保每一件預製構件的品質，從原材料檢驗、工廠生產到現場安裝，均遵循國際及本地標準，並設有多重檢測環節。透過智能化設備與精細化監控，我們確保產品尺寸精準、性能穩定，為合作夥伴提供可靠、安全、可持續的建築解決方案。",
        "qm_cert_desc_2": "OPL在設計、生產、品質及環保方面，已獲香港品質保證局頒發的 ISO9001 及 ISO14001 認證，充分肯定我們的專業水平。同時，東莞預製件廠的職業健康與安全管理亦獲得國家認可監督機構——埃爾維質量認證中心的評定及證書，進一步彰顯我們對安全與責任的承諾。",
        "env_protect_title": "環境保護",
        "env_protect_desc": "OPL 致力於在所有業務運營中實施環境保護和可持續發展實踐。",
        "qm_title": "質量管理",
        "qm_policy_title": "質量方針",
        "qm_policy_desc": "鴻輝預製件有限公司的目標是按照 ISO9001 國際標準的要求運作，生產並供應令客戶滿意的預製混凝土產品。",
        "qm_control_title": "質量控制",
        "qm_control_desc": "全面的質量檢驗系統：進料檢驗、過程檢驗、成品檢驗。",
        "tbl_level_1": "第一級",
        "tbl_level_2": "第二級",
        "tbl_level_3": "第三級",
        "cert_title": "質量認證",
        "cert_desc": "ISO9001 和 14001 證書由 HKQAA 頒發給 OPL。OPL 是 QSPSC 認證的預製混凝土生產商之一。",
        "careers_title": "事業發展",
        "join_us_title": "加入我們",
        "join_us_desc": "在鴻輝，我們重視人才發展，提供優良的工作環境和專業成長機會。",
        "job_eng_title": "工程職位",
        "job_eng_desc": "尋找經驗豐富的工程師加入我們的團隊。",
        "job_qc_title": "質量控制",
        "job_qc_desc": "負責產品質量檢驗和控制。",
        "job_pm_title": "項目管理",
        "job_pm_desc": "管理大型建設項目，協調團隊資源。",
        "job_opp_title": "職業機會",
        "job_opp_desc_1": "我們誠邀有志之士加入團隊，共同開拓未來。本公司重視人才，並提供完善的培訓、福利及具競爭力的薪酬待遇。如欲申請，請點擊「<a href='#' style='color:#4CAF50; text-decoration:underline;'>按此申請</a>」並完成線上職位申請表。",
        "job_opp_desc_2": "所有求職申請將由本公司授權人員以嚴格保密方式處理，並僅限於招聘用途。若申請人於截止日期後三個月內未收到通知，則可視為未獲錄用。我們會在六個月後安全銷毀所有未獲聘用申請者的資料。若中英文版本之間有任何差異，均以英文版本為準。",
        "interested_title": "有興趣加入我們吗？",
        "interested_desc": "請聯繫我們以了解更多工作機會。",
        "contact_title": "聯絡我們",
        "general_inquiry": "一般查詢",
        "head_office": "總辦事處",
        "domestic_address": "國內地址",
        "contact_page_title": "聯絡我們",
        "contact_hq": "總公司",
        "contact_factory": "東莞廠",
        "contact_hq_full": "鴻輝預製件有限公司 (總公司)",
        "contact_factory_full": "東莞鴻輝建築材料製品有限公司 (東莞廠)",
        "contact_hq_address": "地址: 香港葵芳興芳路223號新都會廣場第1座22樓2201室",
        "contact_hq_tel": "電話: (852) 2559 5765",
        "contact_hq_fax": "傳真: (852) 2517 0873",
        "contact_hq_email": "電郵: opl-enquiry@orientfunds.com.hk",
        "contact_factory_address": "國內廠址: 廣東省東莞市沙田鎮聯檢路3號 郵編 523990",
        "contact_factory_tel": "電話: (86) 769 8886 8880",
        "contact_factory_fax": "傳真: (86) 769 8886 8820",
        "val_title": "核心價值",
        "val_goal_title": "目標",
        "val_goal_desc": "成為城市建設最可靠的預製構件供應商。每一件預製構件，都是承載城市夢想的基石。透過品質、創新與責任，讓橋樑、高樓與道路更穩固、更美好。",
        "val_mission_title": "使命",
        "val_combined_title": "目標、使命、願景",
        "val_mission_desc": "以優質混凝土及伊諾邦建材為城市注入生命力。我們承諾為合作夥伴提供可靠、準時、具競爭力的支持，並為社會打造安全、環保、可持續的建材，為後代建立經得起時間考驗的基礎。",
        "val_vision_title": "願景",
        "val_vision_desc": "成為香港最具影響力的綠色建材品牌，推動城市邁向低碳未來。透過智能供應鏈與專業代理服務，讓科技與環保並肩前行，承載世代的夢想與希望。",
        "mile_title": "里程碑",
        "milestone_desc_1998": "公司成立，專注承接房署及房協工程。",
        "milestone_desc_2002": "業務拓展至私人工程，開始承接大型私人項目。",
        "milestone_desc_2019": "投入研發 MiC 技術，推出首個鴻輝石矢 MiC 產品。",
        "milestone_desc_2022": "成功研發並推出輕石矢間牆板，正式進入市場。<br><br>獲香港品質保證局（HKQAA）淨零排放認證，成為推動淨零碳排放的先驅機構。",
        "milestone_desc_2023": "開始研發鋼/石矢 MiC，並命名為「簡悅屋」。",
        "milestone_desc_2024": "全預製輕質混凝土牆板獲得專利認證。",
        "awards_title": "獎項及嘉許",
        "awards_desc": "榮獲多項產業認証和嘉許",
        "about_hongfai_title": "關於鴻輝",
        "website_label": "網頁: ",
        "sister_title": "關聯公司",
        "sister_desc": "永輝混凝土(香港)有限公司與鴻輝預製件有限公司是關聯公司，總部設於香港，專注於混凝土業務。兩家公司秉承專業精神與創新理念，致力提供高品質的混凝土產品及解決方案，服務涵蓋建築、基建及多元化工程項目。憑藉香港的地理優勢與完善的物流網絡，企業能高效滿足客戶需求，並持續拓展業務版圖。",
        "about_hongfai_desc": "鴻輝自1998年成立以來，專注高品質製造與跨境服務。公司於東莞沙田設立現代化廠房，依水而建，地理位置優越，天然臨近水路，為高效運輸提供獨特優勢。廠房距離香港僅一百多公里，交通網絡四通八達。水路運輸至港約需6小時，經皇崗、蓮塘或深圳灣口岸車程亦僅三個多小時。憑藉此戰略區位，鴻輝能迅速連接粵港兩地，為合作夥伴提供高效可靠的跨境供應鏈支持。<br><br>鴻輝擁有完善的生產與物流設施，包括石矢廠、堆放場、沙石倉及十個全天候生產車間，即使在惡劣天氣下亦能保持高效運作，確保品質與進度。廠區設有活動雨棚、電動石矢車及滑移裝載機，提升生產與裝修效率。倉存區面積達 25,000 平方米，現用作預製件外牆貨存。公司更設有獨立碼頭，可處理三十噸以上產品並容納大型船舶，配合成熟的陆路運輸，實現海陸暢通無阻。",
        "cert_patent_title": "資格認證及專利",
        "iso_desc": "ISO 認證：由第三方機構審核，確保管理體系符合國際標準。",
        "patent_desc": "專利：由政府授權，保障技術或設計的獨占使用權。",
        "pqm_title": "預製件質量管理",
        "pqm_section_title": "優質預製件，守護低碳未來",
        "pqm_desc": "我們以嚴謹流程確保每一件預製構件的品質，從原材料檢驗、工廠生產到現場安裝，均遵循國際及本地標準，並設有多重檢測環節。透過智能化設備與精細化監控，產品尺寸更準確、性能更穩定，大幅減少現場施工浪費及二次修補，從而降低整體碳排放，為合作夥伴提供可靠、安全、真正可持續的綠色建築解決方案。",
        "iso14001_text": "ISO 14001:2015<br>證書編號：CC 5665",
        "iso9001_text": "ISO 9001:2015<br>證書編號：CC 1538",
        "net_zero_title": "推動淨零貢獻的先驅機構",
        "net_zero_desc": "於2022年，鴻輝正式參與由香港品質保證局（HKQAA）推行的「淨零排放認證計劃」，以落實其對淨零排放的承諾。憑藉這些努力，鴻輝獲表揚為在推動淨零碳排放倡議方面作出卓越貢獻的先驅機構，彰顯其在促進業界可持續發展方面的領導地位。",
        "three_inspection_title": "三檢制度",
        "three_inspection_section_title": "三檢制度: 確保耐用低碳建築",
        "three_inspection_desc": "鴻輝品質監控組對所有產品進行嚴密監察，確保交付客戶的均為優質耐用產品。公司全面推行「三檢制度」——自檢、複檢及專檢，以保障品質穩定。生產部與品質監控組負責自檢及複檢，中山辦每週前往東莞廠進行專檢，形成多層次品質把關機制。透過嚴格三檢，大幅減少產品缺陷及日後維修需求，從而延長建築壽命、降低全生命周期碳排放，為環境提供真正長遠的保護。",
        "insp_self": "自檢 (生產部)",
        "insp_re": "複檢 (品質組)",
        "insp_special": "專檢 (中山辦)",
        "traceability_title": "一行交一行",
        "traceability_section_title": "一行交一行: 追溯系統，減少資源浪費",
        "traceability_desc": "鴻輝以「一行交一行」為原則，透過QR Code全程追蹤生產流程。從鐵籠捆紮、模具安裝及澆注混凝土，到修補工序及成品檢驗，每一步均有詳細記錄。若成品日後出現問題，系統可即時追溯至相關生產工人及驗收人員。這種精準追溯機制有效避免重工及物料浪費，降低生產過程中的碳足跡，確保每一件產品都真正符合環保可持續標準。"
    },
    "cn": {
        "nav_home": "首页",
        "nav_about": "关于我们",
        "breadcrumb_home": "主页",
        "nav_business": "公司业务",
        "nav_sustainability": "可持续发展",
        "nav_news": "最新动态",
        "nav_careers": "事业发展",
        "nav_contact": "联络我们",
        "completed_projects": "我们参与的著名项目",
        "btn_switch_en": "EN",
        "btn_switch_zh": "繁",
        "btn_switch_cn": "简",
        "footer_intro": "鸿辉预制件有限公司成立于1998年，专门从事预制混凝土构件的生产和供应。",
        "footer_quick_links": "快速链接",
        "footer_contact_title": "联络我们",
        "footer_headquarters": "总公司：",
        "footer_factory": "东莞厂房：",
        "footer_copyright": "Copyright © 2026鸿辉预制件有限公司．版权所有。",
        "hero_title": "克服困难，开拓新路",
        "index_about_title": "关于鸿辉",
        "index_about_desc": "鸿辉是一家专注于预制件的公司，秉承「以心建家」的精神，勇于克服困难，不断开拓新路。我们坚持以专业与创新为核心，致力为客户提供优质可靠的建筑解决方案。",
        "btn_learn_more": "了解更多 ▶",
        "section_projects": "工程项目",
        "section_strength": "公司实力",
        "stat_years": "年专业经验",
        "stat_projects": "成功项目",
        "stat_factory": "平方米厂房",
        "cta_title": "公司实力",
        "cta_desc": "了解更多关于我们的服务和项目",
        "btn_contact_us": "联络我们",
        "about_title": "关于我们",
        "about_intro_title": "公司简介",
        "about_profile_title": "公司概况",
        "about_profile_desc": "鸿辉预制件有限公司成立于1998年。我们的工厂位于东莞市沙田镇。我们是一家全资企业，投资超过8000万港元，占地面积超过80,000平方米，拥有天然水道，水路运输便利。",
        "about_location_title": "厂房位置",
        "about_location_desc": "东莞厂房距离香港100公里，交通网络完善。厂房位于珠江狮子洋入口处。海路前往香港仅需6小时。经陆路从皇岗或文锦渡前往香港需时2小时。",
        "core_values": "核心价值",
        "facilities": "设施",
        "zone_one_title": "第一工区 - 主力生产楼宇预制件",
        "zone_one_desc": "第一工区由5个有盖车间、堆场和混凝土搅拌站组成。5个有盖车间确保在各种天气条件下的高质量和准时生产。我们有能力同时生产相当于25座楼宇的预制产品，即处理最少100套模具，日产量超过700吨。",
        "zone_two_title": "第二工区 - 大型构件生产",
        "zone_two_desc": "第二工区铸造场和堆场占地25,000平方米。配备2台龙门吊机（各80吨和50吨）。主要用于生产重型预制构件，如管片、大型预制梁/柱和外墙、隔音屏障板等。",
        "jetty_title": "码头",
        "jetty_desc": "我们的码头可停靠超过10,000吨的驳船。配有2套固定吊机（150吨和80吨），方便装载大型预制构件。",
        "tech_advantage_title": "技术优势",
        "tech_advantage_desc": "定期与知名机构（如香港大学、理工大学）及组织举办预制件研讨会。",
        "business_products_title": "产品",
        "prod_mic": "MiC组装合成建筑法",
        "prod_wall_panel": "轻质混凝土间墙板",
        "prod_facade": "佛沙",
		"prod_steel_mic": "钢结构组装合成建筑法",
        "prod_steel_mic_ext": "钢结构组装合成建筑法 (外观)",
        "prod_steel_mic_int": "钢结构组装合成建筑法 (室内装修)",
        "prod_conc_mic": "全混凝土组装合成建筑法",
        "prod_conc_mic_ext": "全混凝土组装合成建筑法 (外观)",
        "prod_conc_mic_int": "全混凝土组装合成建筑法 (室内装修)",
        "prod_stair": "楼梯",
        "prod_balcony": "露台",
        "prod_ext_wall": "外墙",
        "prod_chute": "垃圾槽",
        "prod_semi_slab": "半楼板",
        "prod_conc_slab": "挡土墙板",
        "proj_keitak": "启德",
        "proj_cullinan_harbour": "天玺 • 海",
        "proj_tinshuiwai": "天水围",
        "proj_yoho_west": "Yoho West",
        "proj_saisha": "西沙",
        "proj_sierra_sea": "Sierra Sea",
        "proj_cullinan_sky": "天玺 • 天",
        "proj_tuenmun": "屯门",
        "proj_novoland": "NOVOLAND",
        "proj_tsuenwan": "荃湾",
        "proj_1_sha_tsui_rd": "环贸广场",
        "proj_pakshekkok": "白石角",
        "proj_university_hill": "University Hill",
        "proj_yuenlong": "元朗",
        "proj_hakopo_mockup": "下高埔村全混凝土MiC示范单位",
        "proj_go_aqua": "Go Aqua",
        "proj_hakopo_hybrid_office": "下高埔钢结构MiC写字楼",
        "proj_yoho_hub_2": "The YOHO Hub 2期",
        "proj_shatin": "沙田",
        "proj_shatin_name": "珑珀山",
        "proj_taikoktsui": "大角咀",
        "proj_taikoktsui_name": "傲寓",
        "proj_tsingyi": "青衣",
        "proj_tsingyi_name": "明翘汇",
        "proj_southisland": "港岛南",
        "proj_southisland_name": "扬海",
        "proj_saiyingpun": "西营盘",
        "proj_saiyingpun_name": "西边街15号",
        "proj_year_kaitak_harbour": "2024年建成",
        "proj_year_2025": "2025年建成",
        "proj_year_2024": "2024年建成",
        "proj_year_tinshuiwai": "2024年建成",
        "proj_year_saisha": "2024年建成",
        "proj_year_kaitak_sky": "2023年建成",
        "proj_year_novoland": "2023年建成",
        "proj_year_sha_tsui_rd": "2021年建成",
        "proj_year_university_hill": "2022年建成",
        "proj_year_yoho_hub_2": "2022年建成",
        "proj_year_st_michel": "2021年建成",
        "proj_year_le_moment": "2020年建成",
        "proj_year_grand_marine": "2021年建成",
        "proj_year_la_marina": "2021年建成",
        "recent_projects_title": "近5年内完成的工程项目",
        "proj_2025_1": "山顶文辉道2-8号",
        "proj_2025_2": "雅盈峰",
        "proj_2025_3": "云向",
        "proj_2025_4": "滶晨 - 港岛南岸5A期",
        "proj_2025_5": "煥然懿居",
        "proj_2025_6": "映居",
        "proj_2025_7": "古洞第278地段",
        "proj_2025_8": "启德第2B1区",
        "proj_2024_1": "MiC 单位Mockup - 元朗下高埔村",
        "proj_2024_2": "天玄·海",
        "proj_2024_3": "GO PARK Aqua",
        "proj_2024_4": "MiC地盘写字楼 - 元朗下高埔村",
        "proj_2024_5": "MiC地盘写字楼 - 古洞北 (Area 25)",
        "proj_2024_6": "屯门扫管笀第496号地段",
        "proj_2024_7": "Sierra Sea 第1期",
        "proj_2024_8": "YOHO WEST",
        "proj_2023_1": "沙田乙明邨松悦楼",
        "proj_2023_2": "天玄·天",
        "proj_2023_3": "京汇广场",
        "proj_2023_4": "NOVO LAND 第2期",
        "proj_2023_5": "NOVO LAND 第3期",
        "proj_2023_6": "Sierra Sea 第2A期",
        "proj_2022_1": "蔚蓝东岸",
        "proj_2022_2": "NOVO LAND 第1期",
        "proj_2022_3": "ONE SOHO",
        "proj_2022_4": "天泷",
        "proj_2022_5": "The YOHO Hub",
        "proj_2022_6": "University Hill",
        "proj_2021_1": "太子道西233号",
        "proj_2021_2": "环贸广场",
        "proj_2021_3": "KENNEDY 38",
        "proj_2021_4": "扬海",
        "proj_2021_5": "芳菲",
        "proj_2021_6": "ONE INNOVALE",
        "proj_2021_7": "明翘汇",
        "proj_2021_8": "映筑",
        "proj_2021_9": "荟蓝",
        "proj_2021_1_dev": "新鸿基地产/会德丰地产",
        "proj_2021_2_dev": "亿京发展及策划有限公司",
        "proj_2021_3_dev": "恒基兆业、新鸿基地产及会德丰地产",
        "proj_2021_4_dev": "信置 / 港铁 / 嘉里建设",
        "proj_2021_5_dev": "协成行",
        "proj_2021_6_dev": "恒基兆业地产",
        "proj_2021_7_dev": "佳明集团",
        "proj_2021_8_dev": "市建局/恒基兆业",
        "proj_2021_9_dev": "宏安地产",
        "related_business_title": "相关业务",
        "related_concrete_title": "混凝土",
        "related_concrete_desc": "我们的姊妹公司 - 永辉混凝土(香港)有限公司，专注于高品质混凝土及预制组件的生产与供应。凭借完善的生产设施与严格的品质监控，永辉混凝土为紧密的合作伙伴提供稳定、可靠的建材支持。透过各部门协作，我们确保施工进度与成本效益，同时推动创新技术的应用，为各类建筑项目打造坚实基础。",
        "website_label": "网站",
        "qualifications_title": "专业资格",
        "qualifications_placeholder": "专业资格内容将在此处添加。",
        "business_title": "公司业务",
        "eng_projects": "工程项目",
        "cat_residential": "住宅楼宇",
        "cat_infrastructure": "基建",
        "cat_domestic": "国内澳门",
        "tbl_project_name": "项目名称",
        "tbl_product": "预制混凝土产品",
        "tbl_developer": "发展商",
        "tbl_period": "施工期",
        "sus_title": "可持续发展",
        "env_commitment_title": "环境承诺",
        "env_commitment_desc": "我们深知城市发展必须兼顾环境保护，鸿辉持续推动创新与改进，减少建筑对自然的影响，为社会与未来世代守护可持续的生态。",
        "qm_cert_title": "质量管理及品质认证",
        "qm_cert_desc_1": "我们以严谨的流程确保每一件预制构件的品质，从原材料检验、工厂生产到现场安装，均遵循国际及本地标准，并设有多重检测环节。透过智能化设备与精细化监控，我们确保产品尺寸精准、性能稳定，为合作伙伴提供可靠、安全、可持续的建筑解决方案。",
        "qm_cert_desc_2": "OPL在设计、生产、品质及环保方面，已获香港品质保证局颁发的 ISO9001 及 ISO14001 认证，充分肯定我们的专业水平。同时，东莞预制件厂的职业健康与安全管理亦获得国家认可监督机构——埃尔维质量认证中心的评定及证书，进一步彰显我们对安全与责任的承诺。",
        "env_protect_title": "环境保护",
        "env_protect_desc": "OPL 致力于在所有业务运营中实施环境保护和可持续发展实践。",
        "qm_title": "质量管理",
        "qm_policy_title": "质量方针",
        "qm_policy_desc": "鸿辉预制件有限公司的目标是按照 ISO9001 国际标准的要求运作，生产并供应令客户满意的预制混凝土产品。",
        "qm_control_title": "质量控制",
        "qm_control_desc": "全面的质量检验系统：进料检验、过程检验、成品检验。",
        "tbl_level_1": "第一级",
        "tbl_level_2": "第二级",
        "tbl_level_3": "第三级",
        "cert_title": "质量认证",
        "cert_desc": "ISO9001 和 14001 证书由 HKQAA 颁发给 OPL。OPL 是 QSPSC 认证的预制混凝土生产商之一。",
        "careers_title": "事业发展",
        "join_us_title": "加入我们",
        "join_us_desc": "在鸿辉，我们重视人才发展，提供优良的工作环境和专业成长机会。",
        "job_eng_title": "工程职位",
        "job_eng_desc": "寻找经验丰富的工程师加入我们的团队。",
        "job_qc_title": "质量控制",
        "job_qc_desc": "负责产品质量检验和控制。",
        "job_pm_title": "项目管理",
        "job_pm_desc": "管理大型建设项目，协调团队资源。",
        "job_opp_title": "职业机会",
        "job_opp_desc_1": "我们诚邀有志之士加入团队，共同开拓未来。本公司重视人才，并提供完善的培训、福利及具竞争力的薪酬待遇。如欲申请，请点击「<a href='#' style='color:#4CAF50; text-decoration:underline;'>按此申请</a>」并完成线上职位申请表。",
        "job_opp_desc_2": "所有求职申请将由本公司授权人员以严格保密方式处理，并仅限于招聘用途。若申请人于截止日期后三个月内未收到通知，则可视为未获录用。我们会在六个月后安全销毁所有未获聘用申请者的资料。若中英文版本之间有任何差异，均以英文版本为准。",
        "interested_title": "有兴趣加入我们吗？",
        "interested_desc": "请联系我们以了解更多工作机会。",
        "contact_title": "联络我们",
        "general_inquiry": "一般查询",
        "head_office": "总办事处",
        "domestic_address": "国内地址",
        "contact_page_title": "联络我们",
        "contact_hq": "总公司",
        "contact_factory": "东莞厂",        "contact_hq_full": "鸿辉预制件有限公司 (总公司)",
        "contact_factory_full": "东莞鸿辉建筑材料制品有限公司 (东莞厂)",        "contact_hq_address": "地址: 香港葵芳兴芳路223号新都会广场第1座22楼2201室",
        "contact_hq_tel": "电话: (852) 2559 5765",
        "contact_hq_fax": "传真: (852) 2517 0873",
        "contact_hq_email": "电邮: opl-enquiry@orientfunds.com.hk",
        "contact_factory_address": "国内厂址: 广东省东莞市沙田镇联检路3号 邮编 523990",
        "contact_factory_tel": "电话: (769) 8886 8880",
        "contact_factory_fax": "传真: (769) 8886 8820",
        "val_title": "核心价值",
        "val_goal_title": "目标",
        "val_goal_desc": "成为城市建设最可靠的预制构件供应商。每一件预制构件，都是承载城市梦想的基石。透过品质、创新与责任，让桥梁、高楼与道路更稳固、更美好。",
        "val_mission_title": "使命",
        "val_combined_title": "目标、使命、愿景",
        "val_mission_desc": "以优质混凝土及伊诺邦建材为城市注入生命力。我们承诺为合作伙伴提供可靠、准时、具竞争力的支持，并为社会打造安全、环保、可持续的建材，为后代建立经得起时间考验的基础。",
        "val_vision_title": "愿景",
        "val_vision_desc": "成为香港最具影响力的绿色建材品牌，推动城市迈向低碳未来。透过智能供应链与专业代理服务，让科技与环保并肩前行，承载世代的梦想与希望。",
        "mile_title": "里程碑",
        "mile_1998_label": "主力房署及房协工程",
        "mile_1998_sublabel": "公司成立，主力承接房署及房协工程。",
        "mile_2002_label": "主力私人工程",
        "mile_2002_sublabel": "开始承接私人工程。",
        "milestone_desc_1998": "公司成立，专注承接房署及房协工程。",
        "milestone_desc_2002": "业务拓展至私人工程，开始承接大型私人项目。",
        "milestone_desc_2019": "开始研发 MiC 技术，推出首个鸿辉石矢 MiC 产品。",
        "milestone_desc_2022": "成功研发并推出轻石矢间墙板，正式进入市场。<br><br>获香港品质保证局（HKQAA）净零排放认证，成为推动净零碳排放的先驱机构。",
        "milestone_desc_2023": "开始研发钢/石矢 MiC，并命名为「简悦屋」。",
        "milestone_desc_2024": "全预制轻质混凝土墙板获得专利认证。",
        "awards_title": "奖项及嘉许",
        "awards_desc": "荣获多项产业认证和嘉许",
        "about_hongfai_title": "关于鸿辉",
        "website_label": "网页: ",
        "sister_title": "关联公司",
        "sister_desc": "永辉混凝土(香港)有限公司与鸿辉预制件有限公司是关联公司，总部设于香港，专注于混凝土业务。两家公司秉承专业精神与创新理念，致力提供高品质的混凝土产品及解决方案，服务涵盖建筑、基建及多元化工程项目。凭借香港的地理优势与完善的物流网络，企业能高效满足客户需求，并持续拓展业务版图。",
        "about_hongfai_desc": "鸿辉自1998年成立以来，专注高品质制造与跨境服务。公司于东莞沙田设立现代化厂房，依水而建，地理位置优越，天然临近水路，为高效运输提供独特优势。厂房距离香港仅一百多公里，交通网络四通八达。水路运输至港约需6小时，经皇岗、莲塘或深圳湾口岸车程亦仅三个多小时。凭借此战略区位，鸿辉能迅速连接粤港两地，为合作伙伴提供高效可靠的跨境供应链支持。<br><br>鸿辉拥有完善的生产与物流设施，包括混凝土厂、堆放场、沙石仓及十个全天候生产车间，即使在恶劣天气下亦能保持高效运作，确保品质与进度。厂区设有活动雨棚、电动混凝土车及滑移装载机，提升生产与装修效率。仓存区面积达25,000平方米，现用作预制件外墙货存。公司更设有独立码头，可处理三十吨以上产品并容纳大型船舶，配合成熟的陆路运输，实现海陆畅通无阻。",
        "cert_patent_title": "资格认证及专利",
        "iso_desc": "ISO 认证：由第三方机构审核，确保管理体系符合国际标准。",
        "patent_desc": "专利：由政府授权，保障技术或设计的独占使用权。",
        "pqm_title": "预制件质量管理",
        "pqm_section_title": "优质预制件，守护低碳未来",
        "pqm_desc": "我们以严谨流程确保每一件预制构件的品质，从原材料检验、工厂生产到现场安装，均遵循国际及本地标准，并设有多重检测环节。透过智能化设备与精细化监控，产品尺寸更准确、性能更稳定，大幅减少现场施工浪费及二次修补，从而降低整体碳排放，为合作伙伴提供可靠、安全、真正可持续的绿色建筑解决方案。",
        "iso14001_text": "ISO 14001:2015<br>证书编号：CC 5665",
        "iso9001_text": "ISO 9001:2015<br>证书编号：CC 1538",
        "net_zero_title": "推动净零贡献的先驱机构",
        "net_zero_desc": "于2022年，鸿辉正式参与由香港品质保证局（HKQAA）推行的“净零排放认证计划”，以落实其对净零排放的承诺。凭借这些努力，鸿辉获表扬为在推动净零碳排放倡议方面作出卓越贡献的先驱机构，彰显其在促进业界可持续发展方面的领导地位。",
        "three_inspection_title": "三检制度",
        "three_inspection_section_title": "三检制度: 确保耐用低碳建筑",
        "three_inspection_desc": "鸿辉品质监控组对所有产品进行严密监察，确保交付客户的均为优质耐用产品。公司全面推行「三检制度」——自检、复检及专检，以保障品质稳定。生产部与品质监控组负责自检及复检，中山办每周前往东莞厂进行专检，形成多层次品质把关机制。透过严格三检，大幅减少产品缺陷及日后维修需求，从而延长建筑寿命、降低全生命周期碳排放，为环境提供真正长远的保护。",
        "insp_self": "自检 (生产部)",
        "insp_re": "复检 (品质组)",
        "insp_special": "专检 (中山办)",
        "traceability_title": "一行交一行",
        "traceability_section_title": "一行交一行: 追溯系统，减少资源浪费",
        "traceability_desc": "鸿辉以“一行交一行”为原则，透过QR Code全程追踪生产流程。从铁笼捆扎、模具安装及浇注混凝土，到修补工序及成品检验，每一步均有详细记录。若成品日后出现问题，系统可即时追溯至相关生产工人及验收人员。这种精准追溯机制有效避免重工及物料浪费，降低生产过程中的碳足迹，确保每一件产品都真正符合环保可持续标准。"
    },
};

document.addEventListener('DOMContentLoaded', () => {
    const savedLang = localStorage.getItem('site_lang') || 'zh';
    updatePageLanguage(savedLang);
});

function switchToEnglish() {
    updatePageLanguage('en');
}

function switchToChinese() {
    updatePageLanguage('zh');
}

function switchToSimplified() {
    updatePageLanguage('cn');
}

function updatePageLanguage(lang) {
    localStorage.setItem('site_lang', lang);
    if (lang === 'en') {
        document.documentElement.lang = 'en';
    } else if (lang === 'cn') {
        document.documentElement.lang = 'zh-CN';
    } else {
        document.documentElement.lang = 'zh-HK';
    }

    const elements = document.querySelectorAll('[data-i18n]');
    elements.forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (translations[lang] && translations[lang][key]) {
             if (translations[lang][key].includes('<')) {
                el.innerHTML = translations[lang][key];
            } else {
                el.innerText = translations[lang][key];
            }
        }
    });

    const btnEn = document.querySelector('.btn-en');
    const btnZh = document.querySelector('.btn-zh');
    
    // Update active class for buttons
    // We will clean up the button classes in HTML to be easy to select
    if (document.querySelectorAll('.lang-btn').length > 0) {
        document.querySelectorAll('.lang-btn').forEach(btn => {
            const text = btn.textContent.trim();
            if (text === 'EN') {
                if (lang === 'en') btn.classList.add('active');
                else btn.classList.remove('active');
            } else if (text === '繁' || text === '中') {
                if (lang === 'zh') btn.classList.add('active');
                else btn.classList.remove('active');
            } else if (text === '简') {
                if (lang === 'cn') btn.classList.add('active');
                else btn.classList.remove('active');
            }
        });
    }

    // Update ISO images in sustainability.html
    const iso14001Img = document.getElementById('img-iso14001');
    const iso9001Img = document.getElementById('img-iso9001');
    
    if (iso14001Img && iso9001Img) {
        if (lang === 'en') {
            iso14001Img.src = 'img/opl-website-img/iso14001_eng.png';
            iso9001Img.src = 'img/opl-website-img/iso9001_eng.png';
        } else {
            iso14001Img.src = 'img/opl-website-img/iso14001_chinese.png';
            iso9001Img.src = 'img/opl-website-img/iso9001_chinese.png';
        }
    }

    // Update certification images in business.html
    const cert1Img = document.getElementById('img-cert1');
    const cert2Img = document.getElementById('img-cert2');
    const cert3Img = document.getElementById('img-cert3');
    
    if (cert1Img) {
        cert1Img.src = lang === 'en'
            ? 'img/opl-website-img/資格認證及專利1(English).png'
            : 'img/opl-website-img/資格認證及專利1(中).png';
    }
    if (cert2Img) {
        cert2Img.src = lang === 'en'
            ? 'img/opl-website-img/資格認證及專利2(English).png'
            : 'img/opl-website-img/資格認證及專利2(中).png';
    }
    if (cert3Img) {
        cert3Img.src = lang === 'en'
            ? 'img/opl-website-img/資格認證及專利3(English).png'
            : 'img/opl-website-img/資格認證及專利3(中).png';
    }

    // Reveal body after language update is complete
    document.documentElement.classList.remove('lang-en-pending');
    document.documentElement.classList.remove('lang-update-pending');
}
