const translations = {
    "en": {
        "nav_home": "Home",
        "nav_about": "About Us",
        "breadcrumb_home": "Home",
        "nav_business": "Our Business",
        "nav_sustainability": "Sustainability",
        "nav_news": "Latest News",
        "nav_careers": "Careers",
        "nav_contact": "Contact Us",
        "btn_switch_en": "EN",
        "btn_switch_zh": "繁",
        "footer_intro": "Orientfunds Precast Limited was established in 1998, specializing in the production and supply of precast concrete components.",
        "footer_quick_links": "Quick Links",
        "footer_contact_title": "Contact Us",
        "footer_headquarters": "Headquarters:",
        "footer_factory": "Dongguan Factory:",
        "footer_copyright": "© 2026 Orientfunds Precast Ltd. All Rights Reserved.",
        "hero_title": "Building a better future<br>with concrete solutions",
        "index_about_title": "About Orientfunds",
        "index_about_desc": "Orientfunds Precast Limited focuses on providing high-quality precast concrete components for the Hong Kong construction industry. We are committed to improving construction efficiency and safety through innovative technology and strict quality management. With years of experience, we have become a trusted partner in the industry, participating in numerous large-scale residential and infrastructure projects.",
        "btn_learn_more": "Learn More →",
        "section_projects": "Engineering Projects",
        "section_strength": "Company Strength",
        "stat_years": "Years Experience",
        "stat_projects": "Successful Projects",
        "stat_factory": "Sqm Factory",
        "cta_title": "Company Strength",
        "cta_desc": "Learn more about our services and projects",
        "btn_contact_us": "Contact Us",
        "about_title": "About Us",
        "about_intro_title": "Company Introduction",
        "about_profile_title": "Company Profile",
        "about_profile_desc": "Orientfunds Precast Limited was established in 1998. Our factory is located in Shatian Town, Dongguan City. It is a wholly-owned enterprise with an investment of over HK$80 million, covering an area of over 80,000 square meters, with natural waterways and convenient water transportation.",
        "about_location_title": "Factory Location",
        "about_location_desc": "The Dongguan factory is 100km from Hong Kong with a complete transportation network. The factory is located at the entrance of Shiziyang, Pearl River. It takes only 6 hours to reach Hong Kong by sea. It takes 2 hours to reach Hong Kong from Huanggang or Man Kam To by land.",
        "core_values": "Core Values",
        "facilities": "Facilities",
        "zone_one_title": "Zone One - Main Production of Building Prefabricated Components",
        "zone_one_desc": "Zone one consists of 5 covered workshops, storage yards and concrete batching plant. The 5 covered workshops ensure high quality and on-time production under all weather conditions. We are capable of producing precast products equivalent to 25 building blocks simultaneously, i.e., handling at least 100 sets of molds, with daily production exceeding 700 tons.",
        "zone_two_title": "Zone Two - Segment / Large Precast Products",
        "zone_two_desc": "Zone Two casting yard and storage yard cover 25,000 m². It is equipped with 2 gantry cranes (80T and 50T each). It functions for the production of heavy precast units e.g. segments, large precast beams/columns and facades, noise barrier panels etc.",
        "jetty_title": "Jetty",
        "jetty_desc": "Our jetty can take in barge over 10,000 tons. There are 2 sets of fixed cranes (150T and 80T), convenient for loading large precast components.",
        "tech_advantage_title": "Technical Advantage",
        "tech_advantage_desc": "Regular Precast Workshops held with remarkable institutes (e.g. HKU, PolyU) and organizations.",
        "business_products_title": "Products",
        "prod_mic": "MiC Modular Integrated Construction",
        "prod_wall_panel": "Lightweight Concrete Wall Panel",
        "prod_facade": "Façade",
        "proj_shatin": "Shatin",
        "proj_shatin_name": "St Michel",
        "proj_taikoktsui": "Tai Kok Tsui",
        "proj_taikoktsui_name": "Le Moment",
        "proj_tsingyi": "Tsing Yi",
        "proj_tsingyi_name": "The Grand Marine",
        "proj_southisland": "Island South",
        "proj_southisland_name": "La Marina",
        "proj_saiyingpun": "Sai Ying Pun",
        "proj_saiyingpun_name": "15 Western Street",
        "related_business_title": "Related Business",
        "related_concrete_title": "Concrete",
        "related_concrete_desc": "Our sister company - Glorious Concrete (H.K.) Ltd., specializes in the production and supply of high-quality concrete and precast components. With comprehensive production facilities and strict quality control, Glorious Concrete provides stable and reliable building material support for close partners. Through collaboration between departments, we ensure construction progress and cost-effectiveness, while promoting the application of innovative technologies to build a solid foundation for various construction projects.",
        "website_label": "Website",
        "qualifications_title": "Professional Qualifications",
        "qualifications_placeholder": "Content for professional qualifications will be added here.",
        "business_title": "Our Business",
        "eng_projects": "Engineering Projects",
        "cat_residential": "Residential Buildings",
        "cat_infrastructure": "Infrastructure",
        "cat_domestic": "Domestic/Macau",
        "tbl_project_name": "Project Name",
        "tbl_product": "Precast Concrete Product",
        "tbl_developer": "Developer",
        "tbl_period": "Construction Period",
        "sus_title": "Sustainability",
        "env_commitment_title": "Environmental Commitment",
        "env_commitment_desc": "We recognize that urban development must go hand in hand with environmental protection. OPL continuously drives innovation and improvement to minimize the environmental impact of construction, safeguarding a sustainable ecology for society and future generations.",
        "qm_cert_title": "Quality Management & Certification",
        "qm_cert_desc_1": "We ensure the quality of every precast component through rigorous processes. From raw material inspection and factory production to on-site installation, we adhere to international and local standards with multiple inspection checkpoints. Through intelligent equipment and precise monitoring, we ensure dimensional accuracy and stable performance, providing reliable, safe, and sustainable building solutions for our partners.",
        "qm_cert_desc_2": "OPL has been awarded ISO9001 and ISO14001 certifications by the HKQAA for design, production, quality, and environmental protection, fully affirming our professional standards. Meanwhile, our Dongguan factory's Occupational Health and Safety Management has been assessed and certified by the Elvey Quality Certification Center, further demonstrating our commitment to safety and responsibility.",
        "env_protect_title": "Environmental Protection",
        "env_protect_desc": "OPL is committed to implementing environmental protection and sustainability practices in all business operations.",
        "qm_title": "Quality Management",
        "qm_policy_title": "Quality Policy",
        "qm_policy_desc": "It is the objective of Orientfunds Precast Limited to operate in accordance with the requirements of ISO9001, to produce and supply precast concrete products to the satisfaction of customers.",
        "qm_control_title": "Quality Control",
        "qm_control_desc": "Comprehensive Quality Inspection System: Incoming Material Inspection, In-process Inspection, Finished Product Inspection.",
        "tbl_level_1": "Level 1",
        "tbl_level_2": "Level 2",
        "tbl_level_3": "Level 3",
        "cert_title": "Quality Certification",
        "cert_desc": "ISO9001 & 14001 Certificates are accredited to OPL by HKQAA. OPL is one of the QSPSC certified precast concrete producers.",
        "careers_title": "Careers",
        "join_us_title": "Join Us",
        "join_us_desc": "At Orientfunds, we value talent development and provide excellent working environment and professional growth opportunities.",
        "job_eng_title": "Engineering Positions",
        "job_eng_desc": "Looking for experienced engineers to join our team.",
        "job_qc_title": "Quality Control",
        "job_qc_desc": "Responsible for product quality inspection and control.",
        "job_pm_title": "Project Management",
        "job_pm_desc": "Manage large-scale construction projects and coordinate team resources.",
        "job_opp_title": "Job Opportunities",
        "job_opp_desc_1": "We invite aspiring individuals to join our team and explore the future together. We value talent and provide comprehensive training, benefits, and competitive remuneration packages. To apply, please click \"<a href='#' style='color:#4CAF50; text-decoration:underline;'>Apply Here</a>\" and complete the online application form.",
        "job_opp_desc_2": "All job applications will be treated in strict confidence by authorized personnel and used for recruitment purposes only. Applicants not contacted within three months after the deadline may consider their applications unsuccessful. We will safely destroy the data of all unsuccessful applicants after six months. In case of any discrepancy between the English and Chinese versions, the English version shall prevail.",
        "interested_title": "Interested in joining us?",
        "interested_desc": "Please contact us to learn more about job opportunities.",
        "contact_title": "Contact Us",
        "general_inquiry": "General Inquiry",
        "head_office": "Head Office",
        "domestic_address": "Domestic Address",
        "contact_page_title": "Contact Us",
        "contact_hq": "Head Office",
        "contact_factory": "Dongguan Factory",
        "contact_hq_address": "Address: Units Nos. 2201-2211 and 2220-2225, Level 22, Tower 1, Metroplaza, 223 Hing Fong Road, Kwai Fong, N.T.",
        "contact_hq_tel": "Tel: (852) 2559 5765",
        "contact_hq_fax": "Fax: (852) 2517 0873",
        "contact_hq_email": "Email: opl-enquiry@orientfunds.com.hk",
        "contact_factory_address": "Address: No.3 Lianjian Road, Shatian Town, Dongguan, Guangdong, China Postal Code: 523990",
        "contact_factory_tel": "Tel: (769) 8886 8880",
        "contact_factory_fax": "Fax: (769) 8886 8820",
        "val_title": "Core Values",
        "val_goal_title": "Goal",
        "val_goal_desc": "To be the driving force of the city's construction and development.",
        "val_mission_title": "Mission",
        "val_combined_title": "Goal, Mission, Vision",
        "val_mission_desc": "To provide reliable building material solutions, supporting the city's vitality with precast components.",
        "val_vision_title": "Vision",
        "val_vision_desc": "To become the most influential green precast brand in Asia, leading the future of the industry.",
        "mile_title": "Milestones",
        "mile_1998_label": "Main Housing Projects",
        "mile_1998_sublabel": "Company established, mainly undertaking Housing Authority and Housing Society projects.",
        "mile_2002_label": "Private Sector Projects",
        "mile_2002_sublabel": "Started accepting private sector engineering projects.",
        "mile_2019_label": "First OPL MiC Product",
        "mile_2019_sublabel": "Started developing MiC products.",
        "mile_2022_label": "Lightweight Concrete Panel",
        "mile_2022_sublabel": "Successfully developed Lightweight Concrete Panel.",
        "mile_2023_label": "Simplicity House",
        "mile_2023_sublabel": "MiC named Simplicity House. Started developing Steel/Concrete MiC.",
        "awards_title": "Awards & Recognition",
        "awards_desc": "Received multiple industry certifications and recognitions.",
        "about_hongfai_title": "About Orientfunds",
        "about_hongfai_desc": "Orientfunds Precast Limited specializes in the design and production of high-quality precast concrete components, dedicated to providing stable and reliable building material solutions for various projects. With professional technology and innovative thinking, we flexibly meet the needs of different projects, offering efficient, safe, and sustainable solutions for residential buildings to infrastructure. Upholding the promise of 'Building Homes from the Heart', we not only build solid and durable architectural structures but also create a safe and comfortable living environment with exquisite craftsmanship and rigorous management, ensuring every precast component carries the warmth and trust of home."
    },
    "zh": {
        "nav_home": "首頁",
        "nav_about": "關於我們",
        "breadcrumb_home": "主頁",
        "nav_business": "公司業務",
        "nav_sustainability": "可持續發展",
        "nav_news": "最新動態",
        "nav_careers": "事業發展",
        "nav_contact": "聯絡我們",
        "btn_switch_en": "EN",
        "btn_switch_zh": "繁",
        "footer_intro": "鴻輝預製件有限公司成立於1998年，專門從事預製混凝土構件的生產和供應。",
        "footer_quick_links": "快速連結",
        "footer_contact_title": "聯絡我們",
        "footer_headquarters": "總公司：",
        "footer_factory": "東莞廠房：",
        "footer_copyright": "Copyright © 2026鴻輝預製件有限公司．版權所有。",
        "hero_title": "同心協力，精益求精<br>以心打造理想家園",
        "index_about_title": "關於鴻輝",
        "index_about_desc": "鴻輝預製件有限公司專注於為香港建築業提供高品質的預製混凝土構件。我們致力於通過創新技術和嚴格的質量管理，提升建築效率與安全性。憑藉多年的豐富經驗，我們已成為業界信賴的合作夥伴，參與了眾多大型住宅及基建項目。",
        "btn_learn_more": "了解更多 →",
        "section_projects": "工程項目",
        "section_strength": "公司實力",
        "stat_years": "年專業經驗",
        "stat_projects": "成功項目",
        "stat_factory": "平方米廠房",
        "cta_title": "公司實力",
        "cta_desc": "了解更多關於我們的服務和項目",
        "btn_contact_us": "聯絡我們",
        "about_title": "關於我們",
        "about_intro_title": "公司簡介",
        "about_profile_title": "公司概況",
        "about_profile_desc": "鴻輝預製件有限公司成立於1998年。我們的工廠位於東莞市沙田鎮。我們是一家全資企業，投資超過8000萬港元，佔地面積超過80,000平方米，擁有天然水道，水路運輸便利。",
        "about_location_title": "廠房位置",
        "about_location_desc": "東莞廠房距離香港100公里，交通網絡完善。廠房位於珠江獅子洋入口處。海路前往香港僅需6小時。經陸路從皇崗或文錦渡前往香港需時2小時。",
        "core_values": "核心價值",
        "facilities": "設施",
        "zone_one_title": "第一工區 - 主力生產樓宇預製件",
        "zone_one_desc": "第一工區由5個有蓋車間、堆場和混凝土攪拌站組成。5個有蓋車間確保在各種天氣條件下的高質量和準時生產。我們有能力同時生產相當於25座樓宇的預製產品，即處理最少100套模具，日產量超过700噸。",
        "zone_two_title": "第二工區 - 大型構件生產",
        "zone_two_desc": "第二工區鑄造場和堆場佔地25,000平方米。配備2台龍門吊機（各80噸和50噸）。主要用於生產重型預製構件，如管片、大型預製樑/柱和外牆、隔音屏障板等。",
        "jetty_title": "碼頭",
        "jetty_desc": "我們的碼頭可停靠超過10,000噸的駁船。配有2套固定吊機（150噸和80噸），方便裝載大型預製構件。",
        "tech_advantage_title": "技術優勢",
        "tech_advantage_desc": "定期與知名機構（如香港大學、理工大學）及組織舉辦預製件研討會。",
        "business_products_title": "產品",
        "prod_mic": "MiC組裝合成建築法",
        "prod_wall_panel": "輕質混凝土間牆板",
        "prod_facade": "佛沙",
        "proj_shatin": "沙田",
        "proj_shatin_name": "瓏珀山",
        "proj_taikoktsui": "大角咀",
        "proj_taikoktsui_name": "傲寓",
        "proj_tsingyi": "青衣",
        "proj_tsingyi_name": "明翹匯",
        "proj_southisland": "港島南",
        "proj_southisland_name": "揚海",
        "proj_saiyingpun": "西營盤",
        "proj_saiyingpun_name": "西邊街15號",
        "related_business_title": "相關業務",
        "related_concrete_title": "混凝土",
        "related_concrete_desc": "我們的姊妹公司 - 永輝混凝土(香港)有限公司，專注於高品質混凝土及預製組件的生產與供應。憑藉完善的生產設施與嚴格的品質監控，永輝混凝土為緊密的合作夥伴提供穩定、可靠的建材支持。透過各部門協作，我們確保施工進度與成本效益，同時推動創新技術的應用，為各類建築項目打造堅實基礎。",
        "website_label": "網站",
        "qualifications_title": "專業資格",
        "qualifications_placeholder": "專業資格內容將在此處添加。",
        "business_title": "公司業務",
        "eng_projects": "工程項目",
        "cat_residential": "住宅樓宇",
        "cat_infrastructure": "基建",
        "cat_domestic": "國內澳門",
        "tbl_project_name": "項目名稱",
        "tbl_product": "預製混凝土產品",
        "tbl_developer": "發展商",
        "tbl_period": "施工期",
        "sus_title": "可持續發展",
        "env_commitment_title": "環境承諾",
        "env_commitment_desc": "我們深知城市發展必須兼顧環境保護，港興持續推動創新與改進，減少建築對自然的影響，為社會與未來世代守護可持續的生態。",
        "qm_cert_title": "質量管理及品質認證",
        "qm_cert_desc_1": "我們以嚴謹的流程確保每一件預製構件的品質，從原材料檢驗、工廠生產到現場安裝，均遵循國際及本地標準，並設有多重檢測環節。透過智能化設備與精細化監控，我們確保產品尺寸精準、性能穩定，為合作夥伴提供可靠、安全、可持續的建築解決方案。",
        "qm_cert_desc_2": "OPL在設計、生產、品質及環保方面，已獲香港品質保證局頒發的 ISO9001 及 ISO14001 認證，充分肯定我們的專業水平。同時，東莞預製件廠的職業健康與安全管理亦獲得國家認可監督機構——埃爾維質量認證中心的評定及證書，進一步彰顯我們對安全與責任的承諾。",
        "env_protect_title": "環境保護",
        "env_protect_desc": "OPL 致力於在所有業務運營中實施環境保護和可持續發展實踐。",
        "qm_title": "質量管理",
        "qm_policy_title": "質量方針",
        "qm_policy_desc": "鴻輝預製件有限公司的目標是按照 ISO9001 國際標準的要求運作，生產並供應令客戶滿意的預製混凝土產品。",
        "qm_control_title": "質量控制",
        "qm_control_desc": "全面的質量檢驗系統：進料檢驗、過程檢驗、成品檢驗。",
        "tbl_level_1": "第一級",
        "tbl_level_2": "第二級",
        "tbl_level_3": "第三級",
        "cert_title": "質量認證",
        "cert_desc": "ISO9001 和 14001 證書由 HKQAA 頒發給 OPL。OPL 是 QSPSC 認證的預製混凝土生產商之一。",
        "careers_title": "事業發展",
        "join_us_title": "加入我們",
        "join_us_desc": "在鴻輝，我們重視人才發展，提供優良的工作環境和專業成長機會。",
        "job_eng_title": "工程職位",
        "job_eng_desc": "尋找經驗豐富的工程師加入我們的團隊。",
        "job_qc_title": "質量控制",
        "job_qc_desc": "負責產品質量檢驗和控制。",
        "job_pm_title": "項目管理",
        "job_pm_desc": "管理大型建設項目，協調團隊資源。",
        "job_opp_title": "職業機會",
        "job_opp_desc_1": "我們誠邀有志之士加入團隊，共同開拓未來。本公司重視人才，並提供完善的培訓、福利及具競爭力的薪酬待遇。如欲申請，請點擊「<a href='#' style='color:#4CAF50; text-decoration:underline;'>按此申請</a>」並完成線上職位申請表。",
        "job_opp_desc_2": "所有求職申請將由本公司授權人員以嚴格保密方式處理，並僅限於招聘用途。若申請人於截止日期後三個月內未收到通知，則可視為未獲錄用。我們會在六個月後安全銷毀所有未獲聘用申請者的資料。若中英文版本之間有任何差異，均以英文版本為準。",
        "interested_title": "有興趣加入我們吗？",
        "interested_desc": "請聯繫我們以了解更多工作機會。",
        "contact_title": "聯絡我們",
        "general_inquiry": "一般查詢",
        "head_office": "總辦事處",
        "domestic_address": "國內地址",
        "contact_page_title": "聯絡我們",
        "contact_hq": "總公司",
        "contact_factory": "東莞廠",
        "contact_hq_address": "地址: 香港葵芳興芳路223號新都會廣場第1座22樓2201室",
        "contact_hq_tel": "電話: (852) 2559 5765",
        "contact_hq_fax": "傳真: (852) 2517 0873",
        "contact_hq_email": "電郵: opl-enquiry@orientfunds.com.hk",
        "contact_factory_address": "國內廠址: 廣東省東莞市沙田鎮聯檢路3號 郵編 523990",
        "contact_factory_tel": "電話: (769) 8886 8880",
        "contact_factory_fax": "傳真: (769) 8886 8820",
        "val_title": "核心價值",
        "val_goal_title": "目標",
        "val_goal_desc": "成為城市建設最堅實的推動力，每一件預製構件都是承載夢想的基石，透過品質、創新與責任，讓橋樑、高樓與道路更穩固、更美好。",
        "val_mission_title": "使命",
        "val_combined_title": "目標、使命、願景",
        "val_mission_desc": "以建築預製件承托城市生命力，我們承諾為合作伙伴提供可靠、準時、具競爭力的支持，為社會打造安全、環保、可持續的建材，為未來世代留下可信的基礎。",
        "val_vision_title": "願景",
        "val_vision_desc": "成為亞洲最具影響力的綠色預製件品牌，推動城市邁向低碳未來，透過智能生產與智慧物流，打造「未來工廠」，讓科技與環保並肩前行，承載世代的夢想與希望。",
        "mile_title": "里程碑",
        "mile_1998_label": "主力房署及房協工程",
        "mile_1998_sublabel": "公司成立，主力承接房署及房協工程。",
        "mile_2002_label": "主力私人工程",
        "mile_2002_sublabel": "開始承接私人工程。",
        "mile_2019_label": "首個鴻輝石矢MiC產品",
        "mile_2019_sublabel": "開始研發MiC產品。",
        "mile_2022_label": "輕石矢間牆板",
        "mile_2022_sublabel": "成功研發輕石矢間牆板，並應用於實際項目。",
        "mile_2023_label": "簡悅屋",
        "mile_2023_sublabel": "開始研發鋼/石矢MiC，命名為簡悅屋。",
        "awards_title": "獎項及嘉許",
        "awards_desc": "榮獲多項產業認証和嘉許",
        "about_hongfai_title": "關於鴻輝",
        "about_hongfai_desc": "鴻輝預製件有限公司專注於高品質建築預製構件的設計與生產，致力為各類工程提供穩定可靠的建材方案。憑藉專業技術與創新思維，我們能靈活滿足不同項目的需求，從住宅樓宇到基礎設施，均提供高效、安全、可持續的解決方案。秉持「以心建家」的承諾，我們不僅打造堅固耐用的建築基構，更以細緻工藝和嚴謹管理，營造安心舒適的生活環境，讓每一件預製構件都承載著家的溫度與信任。"
    },
};

document.addEventListener('DOMContentLoaded', () => {
    const savedLang = localStorage.getItem('site_lang') || 'zh';
    updatePageLanguage(savedLang);
});

function switchToEnglish() {
    updatePageLanguage('en');
}

function switchToChinese() {
    updatePageLanguage('zh');
}

function updatePageLanguage(lang) {
    localStorage.setItem('site_lang', lang);
    document.documentElement.lang = lang === 'zh' ? 'zh-HK' : 'en';

    const elements = document.querySelectorAll('[data-i18n]');
    elements.forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (translations[lang] && translations[lang][key]) {
             if (translations[lang][key].includes('<')) {
                el.innerHTML = translations[lang][key];
            } else {
                el.innerText = translations[lang][key];
            }
        }
    });

    const btnEn = document.querySelector('.btn-en');
    const btnZh = document.querySelector('.btn-zh');
    
    // Update active class for buttons
    // We will clean up the button classes in HTML to be easy to select
    if (document.querySelectorAll('.lang-btn').length > 0) {
        document.querySelectorAll('.lang-btn').forEach(btn => {
            if (btn.textContent.trim() === 'EN') {
                if (lang === 'en') btn.classList.add('active');
                else btn.classList.remove('active');
            } else if (btn.textContent.trim() === '繁' || btn.textContent.trim() === '中') {
                if (lang === 'zh') btn.classList.add('active');
                else btn.classList.remove('active');
            }
        });
    }
}
